# Credits - https://gist.github.com/mariusv/

    - name: Check if EPEL repo is already configured.
      stat: path={{ epel_repofile_path }}
      register: epel_repofile_result

    - name: Add EPEL repo
      tags: epel
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        async: yes
        gpgkey: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        gpgcheck: yes
        cost: 500
      when:
        - not epel_repofile_result.stat.exists
        - ansible_distribution == 'CentOS'
