---

- name: Create /etc/cron.d directory
  file:
    state: directory
    path: /etc/cron.d
  tags: docker,crond

- name: Deploy crond configuration for the regular autoclean garbage
  copy:
    src: docker-prune.crond
    dest: /etc/cron.d/docker-prune
  tags: docker,crond
